# Generated by Django 5.0.3 on 2024-04-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphgame',
            name='last_reset_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
